sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - 'node'
script:
  - yarn run build
  - yarn jest --coverage
  - yarn danger ci
deploy:
  provider: script
  skip_cleanup: true
  script: yarn semantic-release
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|beta)$
