language: node_js
cache:
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - 'node'
script:
  - yarn run build
  - yarn jest --coverage
  - yarn danger ci
deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn semantic-release

