language: node_js
cache:
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - 'node'
script:
  - npx jest --coverage
  - npx danger ci
after_success:
- npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
