language: node_js
cache:
  directories:
    - "node_modules"
notifications:
  email: false
node_js:
  - 'node'
script:
  - npm run build
  - npx jest --coverage
  - npx danger ci
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release

