apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: plugins-client-sdk
  annotations:
    github.com/project-slug: Staffbase/plugins-client-sdk
    backstage.io/source-location: url:https://github.com/Staffbase/plugins-client-sdk/
    backstage.io/techdocs-ref: dir:.
  tags:
    - javascript
spec:
  type: other
  lifecycle: production
