# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.STAFFBOT_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: yarn install

    - name: Lint code
      run: yarn lint

    - name: Unit test
      run: yarn jest --coverage

  release:
    name: Release
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Remove NPM publish
        if: ${{ github.ref == 'refs/heads/alpha' }}
        run: "sed -i '/public:/d' .releaserc"

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          GITHUB_NPM_TOKEN: ${{ secrets.STAFFBOT_GITHUB_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
