name: Publish TechDocs Site

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/techdocs.yml"

jobs:
  publish-techdocs-site:
    uses: Staffbase/gha-workflows/.github/workflows/template_techdocs.yml@v1.12.0
    with:
      entity-name: plugins-client-sdk
    secrets:
      aws-access-key-id: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
